server:
  # The URL at which the Cranberry instance will be reachable.
  # Cranberry currently does not support running under a subpath.
  self: "http://localhost/"
  # Optional: Different URL for the management interface.
  management: null
  # IPv4 address to bind to. (IPv6 is not supported)
  bind: 0.0.0.0
  # The port on which the HTTP-server should listen.
  port: 8080

database:
  # The host at which the PostgreSQL database can be reached.
  host: localhost
  # The port at which the PostgreSQL database can be reached.
  port: 5432
  # The username to log into the database.
  user: user
  # The password to log into the database.
  password: password
  # The database to conect to
  database: database
  # Extra postgres option string
  options: ""

auth:
  # What permission level should unauthenticated users have?
  #  none:             No permissions.
  #  create_anonymous: Create short links with a random id.
  #  create_named:     Create short links with a custom id.
  #  manage:           Create, view, edit and delete all short links.
  anonymous: "none"
  ldap:
    # Whether Cranberry should allow user login via LDAP.
    enabled: false
    # The host of the LDAP server.
    host: localhost
    # Whether the LDAP server uses TLS.
    tls: false
    # The port of the LDAP server.
    port: 389
    # A dn used to bind to the LDAP server.
    binddn: null
    # The password used to bind to the LDAP server.
    bindpassword: null
    # The base dn to search in.
    basedn: ""
    # An LDAP filter that filters for users. This will be ANDed with a filter for the username.
    usersearch: "(objectClass=person)"
    # Configure, which attributes Cranberry should read.
    attributes:
      # The attribute that contains the username to log in.
      uid: "uid"
      # The attribute that contains the groups, a user is a member of.
      membership: "memberOf"
    # Default permission level for authenticated users
    defaultpermission: "create_anonymous"
    groups:
      # The dn of an LDAP group that allows to create short links with a random id.
      createanonymous: "" 
      # The dn of an LDAP group that allows to create short links with a custom id.
      createnamed: ""
      # The dn of an LDAP group that allows to manage short links.
      manage: ""
  oidc:
    # Whether Cranberry should allow user login via OpenID Connect.
    enabled: false
    # The discovery URL of the OIDC provider.
    discovery: ""
    # The client id for the OIDC provider.
    clientid: ""
    # The client secret for the OIDC provider.
    clientsecret: ""
    # Default permission level for authenticated users
    defaultpermission: "create_anonymous"
    roles:
      # A role from the clientroles claim that has to be present in order for a user to log in.
      # If left empty, no specific role is required.
      login: ""
      # A role from the clientroles claim that grants permission to create anonymous short links.
      createanonymous: ""
      # A role from the clientroles claim that grants permission to create named short links.
      createnamed: ""
      # A role from the clientroles claim that grants permission to manage short links.
      manage: ""
